# -*- coding: utf-8 -*-
"""Proyecto Mineria de datos 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uXWnlRnfzb4PWTdlnmGgKRaJCVz2IkQA
"""

pip install google-genai

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json
import os
import re
import shutil
import graphviz
from scipy import stats
from google import genai
from google.colab import userdata, files

# Configuración de estilos para los gráficos
sns.set_style("whitegrid")

class AnalizadorCSV:
    def __init__(self, file_path: str, api_key: str, output_dir: str = "output"):
        self.file_path = file_path
        self.client = genai.Client(api_key=api_key)
        self.df = None
        self.output_dir = output_dir

        # Diccionario para almacenar descripciones analíticas de cada gráfico
        self.graficos_descripciones = {}

        # Estructura requerida para el resumen según sección 4.6 del PDF
        self.resumen_tecnico = {
            "nombre_dataset": file_path,
            "dimensiones": "",
            "promedio_valores_faltantes": 0,
            "top_correlaciones": [],
            "total_outliers": 0,
            "insights_extra": []
        }

        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def limpiar_output(self):
        """Borra todo el contenido de la carpeta output para iniciar limpio."""
        if os.path.exists(self.output_dir):
            shutil.rmtree(self.output_dir)
            os.makedirs(self.output_dir)
            print(f"🧹 Carpeta '{self.output_dir}' limpiada exitosamente.")

    def descargar_resultados(self):
        """Comprime la carpeta output y la descarga como ZIP."""
        print("📦 Preparando descarga...")
        if not os.path.exists(self.output_dir):
            print("⚠️ No existe la carpeta de output para descargar.")
            return

        # Nombre del archivo zip
        zip_base_name = "reporte_proyecto_mineria"
        shutil.make_archive(zip_base_name, 'zip', self.output_dir)

        zip_file = f"{zip_base_name}.zip"
        print(f"⬇️ Descargando {zip_file}...")
        files.download(zip_file)

    def cargar_y_validar(self) -> bool:
        """Punto 4.2 del PDF: Cargar y Validar Datos"""
        try:
            try:
                self.df = pd.read_csv(self.file_path, encoding='utf-8')
            except UnicodeDecodeError:
                self.df = pd.read_csv(self.file_path, encoding='latin1')

            rows, cols = self.df.shape
            print(f"✅ Dataset cargado. Dimensiones: {rows} filas, {cols} columnas")

            if rows < 2000:
                print("⚠️ Advertencia: El dataset tiene menos de 2000 registros (Requisito del PDF).")
            if cols < 10:
                print("⚠️ Advertencia: El dataset tiene menos de 10 columnas (Requisito del PDF).")

            self.resumen_tecnico["dimensiones"] = f"{rows} filas, {cols} columnas"
            return True
        except Exception as e:
            print(f"❌ Error crítico cargando el dataset: {e}")
            return False

    def generar_diagrama_flujo(self):
        """Genera el diagrama de flujo usando Graphviz y lo guarda como imagen."""
        print("🔀 Generando diagrama de flujo automático...")
        try:
            dot = graphviz.Digraph(comment='Flujo del Proyecto')
            dot.attr(rankdir='TD', dpi='300')
            dot.attr('node', shape='box', style='filled', fillcolor='lightblue', fontname='Helvetica')

            # Definición de Nodos
            dot.node('A', 'Inicio: Carga CSV')
            dot.node('B', 'Validación (Filas/Cols)')
            dot.node('C', 'Análisis Estadístico\n(Moda, Frecuencias)')
            dot.node('D', 'Detección Outliers (IQR)')
            dot.node('E', 'Visualizaciones\n(Hist, Boxplot, Heatmap)')
            dot.node('F', 'Correlaciones (Pearson)')
            dot.node('G', 'Integración IA (Gemini)')
            dot.node('H', 'Generación Reporte PDF')
            dot.node('Z', 'Error / Fin', fillcolor='salmon')

            # Aristas
            dot.edge('A', 'B')
            dot.edge('B', 'C', label='Válido')
            dot.edge('B', 'Z', label='Inválido')
            dot.edge('C', 'D')
            dot.edge('D', 'E')
            dot.edge('E', 'F')
            dot.edge('F', 'G')
            dot.edge('G', 'H')

            output_path = os.path.join(self.output_dir, 'diagrama_flujo')
            dot.render(output_path, format='png', cleanup=True)
            print(f"   Diagrama guardado en: {output_path}.png")

            # Descripción para el diagrama
            self.graficos_descripciones['diagrama_flujo.png'] = "Representación esquemática del flujo de datos automatizado implementado en Python, desde la ingesta cruda hasta la generación del reporte PDF."

        except Exception as e:
            print(f"⚠️ No se pudo generar el diagrama con Graphviz: {e}")

    def analisis_estadistico(self):
        """Punto 4.3 del PDF: Análisis Estadístico (Frecuencias, Moda, Nulos)"""
        print("⚡ Ejecutando Análisis Estadístico...")

        total_celdas = np.prod(self.df.shape)
        total_nulos = self.df.isnull().sum().sum()
        promedio_nulos = (total_nulos / total_celdas) * 100
        self.resumen_tecnico["promedio_valores_faltantes"] = f"{promedio_nulos:.2f}%"

        cat_cols = self.df.select_dtypes(include=['object', 'category']).columns
        for col in cat_cols:
            if not self.df[col].mode().empty:
                moda = self.df[col].mode()[0]
            else:
                moda = "N/A"

            if not self.df[col].value_counts().empty:
                top_freq = self.df[col].value_counts().iloc[0]
            else:
                top_freq = 0

            self.resumen_tecnico["insights_extra"].append(
                f"Columna '{col}': La moda es '{moda}' apareciendo {top_freq} veces."
            )

    def detectar_outliers(self):
        """Parte del Punto 4.6: Calcular Total de Outliers"""
        print("🧮 Detectando Outliers (Método IQR)...")
        num_cols = self.df.select_dtypes(include=np.number).columns
        total_outliers = 0

        for col in num_cols:
            Q1 = self.df[col].quantile(0.25)
            Q3 = self.df[col].quantile(0.75)
            IQR = Q3 - Q1
            lower_bound = Q1 - 1.5 * IQR
            upper_bound = Q3 + 1.5 * IQR

            outliers_col = ((self.df[col] < lower_bound) | (self.df[col] > upper_bound)).sum()
            total_outliers += outliers_col

        self.resumen_tecnico["total_outliers"] = int(total_outliers)
        print(f"   Total de outliers detectados en todo el dataset: {total_outliers}")

    def visualizaciones(self):
        """Punto 4.4 del PDF: Visualizaciones"""
        print("📊 Generando Visualizaciones...")

        num_cols = self.df.select_dtypes(include=np.number).columns
        cat_cols = self.df.select_dtypes(include=['object', 'category']).columns

        # 1. Heatmap de valores faltantes
        plt.figure(figsize=(10, 6))
        sns.heatmap(self.df.isnull(), cbar=False, yticklabels=False, cmap='viridis')
        plt.title("Mapa de Calor de Valores Faltantes")
        self._guardar_grafico("heatmap_nulos")

        # Descripción dinámica Heatmap
        nulos_total = self.df.isnull().sum().sum()
        if nulos_total == 0:
            desc_nulos = "El gráfico muestra un color uniforme, lo que indica que el dataset está completo y no presenta valores nulos en ninguna variable."
        else:
            desc_nulos = f"Las líneas claras en el gráfico indican la posición de los {nulos_total} valores faltantes detectados. Se observan patrones de ausencia que deben ser tratados."
        self.graficos_descripciones["heatmap_nulos.png"] = desc_nulos

        # 2. Histogramas y Boxplots (Numéricas)
        for col in num_cols[:5]:
            fig, ax = plt.subplots(1, 2, figsize=(12, 4))

            # Histograma
            sns.histplot(self.df[col], kde=True, ax=ax[0], color='skyblue')
            ax[0].set_title(f'Histograma: {col}')

            # Boxplot
            sns.boxplot(x=self.df[col], ax=ax[1], color='lightgreen')
            ax[1].set_title(f'Boxplot: {col}')

            self._guardar_grafico(f"distribucion_{col}")

            # Descripción dinámica Distribución
            media = self.df[col].mean()
            std = self.df[col].std()

            # Calculamos outliers específicos para esta columna
            Q1 = self.df[col].quantile(0.25)
            Q3 = self.df[col].quantile(0.75)
            IQR = Q3 - Q1
            outliers_count = ((self.df[col] < (Q1 - 1.5 * IQR)) | (self.df[col] > (Q3 + 1.5 * IQR))).sum()

            desc_dist = (f"A la izquierda, el histograma muestra la distribución de los datos con una media de {media:.2f} y desviación estándar de {std:.2f}. "
                         f"A la derecha, el boxplot revela la dispersión y destaca {outliers_count} valores atípicos (puntos fuera de los bigotes) detectados mediante IQR.")
            self.graficos_descripciones[f"distribucion_{col}.png"] = desc_dist

        # 3. Gráficos de barras (Categóricas)
        for col in cat_cols[:3]:
            if self.df[col].nunique() < 20:
                plt.figure(figsize=(10, 5))
                sns.countplot(y=self.df[col], order=self.df[col].value_counts().index, palette="pastel")
                plt.title(f'Frecuencia: {col}')
                self._guardar_grafico(f"barras_{col}")

                # Descripción dinámica Barras
                top_cat = self.df[col].value_counts().idxmax()
                count_top = self.df[col].value_counts().max()
                desc_barras = (f"Gráfico de frecuencias para la variable categórica '{col}'. "
                               f"Se observa que la categoría predominante es '{top_cat}' con {count_top} ocurrencias, lo que indica la moda de la distribución.")
                self.graficos_descripciones[f"barras_{col}.png"] = desc_barras

    def analisis_correlaciones(self):
        """Punto 4.5 del PDF: Matriz Pearson y Top 5 correlaciones"""
        print("🔗 Analizando Correlaciones...")
        num_df = self.df.select_dtypes(include=np.number)

        if num_df.shape[1] < 2:
            return

        corr_matrix = num_df.corr(method='pearson')

        plt.figure(figsize=(10, 8))
        sns.heatmap(corr_matrix, cmap="coolwarm", annot=True, fmt=".2f")
        plt.title("Matriz de Correlación (Pearson)")
        self._guardar_grafico("heatmap_correlacion")

        corr_unstack = corr_matrix.abs().unstack()
        so = corr_unstack.sort_values(ascending=False)
        so = so[so < 1.0]
        top_corr = so.head(10)

        unique_corrs = []
        seen = set()
        for idx, val in top_corr.items():
            pair = tuple(sorted(idx))
            if pair not in seen:
                seen.add(pair)
                real_val = corr_matrix.loc[idx[0], idx[1]]
                unique_corrs.append(f"{idx[0]} vs {idx[1]}: {real_val:.2f}")
                if len(unique_corrs) == 5:
                    break

        self.resumen_tecnico["top_correlaciones"] = unique_corrs
        print("   Top 5 correlaciones identificadas.")

        # Descripción dinámica Correlación
        if unique_corrs:
            top_pair = unique_corrs[0] # ej "Age vs Salary: 0.85"
            desc_corr = (f"Matriz de coeficientes de Pearson. Los colores rojos intensos indican correlación positiva fuerte y los azules negativa. "
                         f"La relación más significativa encontrada es {top_pair}, lo que sugiere una fuerte dependencia lineal entre estas variables.")
        else:
            desc_corr = "Matriz de correlación de Pearson. No se detectaron correlaciones lineales significativas entre las variables numéricas."

        self.graficos_descripciones["heatmap_correlacion.png"] = desc_corr

    def _guardar_grafico(self, nombre: str):
        path = os.path.join(self.output_dir, f"{nombre}.png")
        plt.savefig(path, bbox_inches='tight')
        plt.close()

    def consultar_ia_generativa(self):
        """Punto 4.6 del PDF: Generación de Insights"""
        print("🤖 Consultando a la IA para el reporte final...")

        prompt = f"""
        Actúa como un experto Analista de Datos. Tengo un dataset con los siguientes metadatos técnicos:

        NOMBRE DATASET: {self.resumen_tecnico['nombre_dataset']}
        DIMENSIONES: {self.resumen_tecnico['dimensiones']}
        PROMEDIO VALORES FALTANTES: {self.resumen_tecnico['promedio_valores_faltantes']}
        TOTAL OUTLIERS DETECTADOS: {self.resumen_tecnico['total_outliers']}

        TOP 5 CORRELACIONES MÁS FUERTES:
        {json.dumps(self.resumen_tecnico['top_correlaciones'], indent=2)}

        OTROS DATOS (MODA/FRECUENCIAS):
        {json.dumps(self.resumen_tecnico['insights_extra'], indent=2)}

        Por favor, genera un reporte en formato Markdown que contenga EXACTAMENTE estas secciones:
        1. **Resumen Ejecutivo**: Una visión general breve del dataset.
        2. **Tres Hallazgos Clave**: Basados en las correlaciones y outliers mostrados.
        3. **Tres Recomendaciones de Preprocesamiento**: Basado en los valores nulos y outliers.
        """

        try:
            response = self.client.models.generate_content(
                model="gemini-2.0-flash",
                contents=prompt
            )
            contenido = response.text

            with open(os.path.join(self.output_dir, "Reporte_Final_IA.md"), "w", encoding="utf-8") as f:
                f.write(contenido)

            return contenido

        except Exception as e:
            print(f"❌ Error en la API de IA: {e}")
            return "No se pudo generar el reporte de IA."

    def generar_conclusiones_automaticas(self):
        """Genera un texto de análisis basado en reglas lógicas deterministas."""
        textos = []

        # --- NUEVO BLOQUE: Resumen Técnico Inicial ---
        # Formatear correlaciones para que no sea una lista muy larga en el resumen
        top_corrs = self.resumen_tecnico['top_correlaciones']
        if top_corrs:
            # Tomamos hasta 5 y si hay más ponemos puntos suspensivos
            corrs_str = ", ".join(top_corrs[:5])
            if len(top_corrs) > 5:
                corrs_str += ", ..."
        else:
            corrs_str = "No se detectaron correlaciones fuertes."

        resumen_bloque = (
            "### Ficha Técnica del Dataset\n"
            f"* **Nombre del Archivo:** {self.resumen_tecnico['nombre_dataset']}\n"
            f"* **Dimensiones:** {self.resumen_tecnico['dimensiones']}\n"
            f"* **Promedio de Valores Faltantes:** {self.resumen_tecnico['promedio_valores_faltantes']}\n"
            f"* **Total de Outliers:** {self.resumen_tecnico['total_outliers']}\n"
            f"* **Correlaciones Principales:** {corrs_str}\n\n"
            "### Diagnóstico Automático Basado en Reglas\n"
        )
        textos.append(resumen_bloque)

        # 1. Análisis de Correlaciones
        if self.resumen_tecnico['top_correlaciones']:
            best_corr_raw = self.resumen_tecnico['top_correlaciones'][0]
            try:
                vars_part, val_part = best_corr_raw.split(':')
                val = float(val_part.strip())
                vars_names = vars_part.split(' vs ')

                tipo = "positiva" if val > 0 else "negativa"
                if abs(val) > 0.8: fuerza = "muy fuerte"
                elif abs(val) > 0.5: fuerza = "considerable"
                else: fuerza = "moderada"

                explicacion_tipo = "aumenta" if val > 0 else "disminuye"

                textos.append(
                    f"**Correlación Dominante:** Se ha detectado una relación lineal **{fuerza} {tipo}** ({val}) entre las variables \\textbf{{{vars_names[0]}}} y \\textbf{{{vars_names[1]}}}. "
                    f"Esto sugiere un patrón claro: cuando una variable aumenta, la otra tiende a {explicacion_tipo} proporcionalmente. "
                    "Este hallazgo es visible en el Mapa de Calor (Heatmap) generado."
                )
            except:
                textos.append(f"**Correlaciones:** Se detectaron patrones de asociación importantes, siendo el más relevante: {best_corr_raw}.")

        # 2. Análisis de Anomalías
        outliers = self.resumen_tecnico['total_outliers']
        if outliers > 0:
            textos.append(
                f"**Integridad de Distribución:** El análisis de rangos intercuartiles (IQR) ha identificado **{outliers} valores atípicos** (outliers) en el conjunto de datos. "
                "La presencia de estos valores extremos se puede observar en los gráficos de caja (Boxplots) y podría sesgar métricas como la media aritmética."
            )
        else:
            textos.append("**Integridad de Distribución:** No se han detectado valores atípicos significativos bajo el criterio estadístico IQR, lo que indica que los datos poseen una dispersión controlada y homogénea.")

        # 3. Análisis de Calidad
        try:
            pct_nulos = float(self.resumen_tecnico['promedio_valores_faltantes'].replace('%',''))
            estado = "crítica" if pct_nulos > 15 else ("aceptable" if pct_nulos < 5 else "mejorable")
            accion = "se requieren técnicas avanzadas de imputación" if pct_nulos > 1 else "el dataset es apto para análisis inmediato"

            textos.append(
                f"**Calidad del Dato:** El dataset presenta una salud **{estado}** en términos de completitud, con un promedio de valores nulos del {pct_nulos}%. "
                f"Basado en esto, {accion}."
            )
        except:
            pass

        return "\n\n".join(textos)

    def generar_latex(self, texto_ia):
        """Genera un archivo .tex con imágenes, descripciones y texto IA."""
        print("📝 Generando archivo LaTeX compilado...")
        tex_path = os.path.join(self.output_dir, "reporte_proyecto.tex")

        # --- Manejo del Logo ---
        logo_source = "Logo.jpg"
        logo_dest = os.path.join(self.output_dir, "Logo.jpg")
        has_logo = False

        if os.path.exists(logo_source):
            try:
                shutil.copy(logo_source, logo_dest)
                has_logo = True
            except Exception as e:
                print(f"   ⚠️ Error copiando el logo: {e}")

        # --- Helper: Escapar caracteres LaTeX ---
        def escape_latex(text):
            chars = {
                "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
                "{": r"\{", "}": r"\}", "~": r"\textasciitilde", "^": r"\textasciicircum"
            }
            return "".join(chars.get(c, c) for c in text)

        # --- Helper: Markdown a LaTeX ---
        def markdown_to_latex(md_text):
            lines = md_text.split('\n')
            latex_lines = []
            in_list = False
            for line in lines:
                line = line.strip()
                if not line:
                    if in_list:
                        latex_lines.append(r"\end{itemize}")
                        in_list = False
                    latex_lines.append("")
                    continue
                if line.startswith('### '):
                    line = r"\subsubsection*{" + escape_latex(line[4:]) + "}"
                elif line.startswith('## '):
                    line = r"\subsection*{" + escape_latex(line[3:]) + "}"
                elif line.startswith('# '):
                    line = r"\section*{" + escape_latex(line[2:]) + "}"
                elif line.startswith('* ') or line.startswith('- '):
                    if not in_list:
                        latex_lines.append(r"\begin{itemize}")
                        in_list = True
                    content = line[2:]
                    if "**" in content:
                        parts = content.split("**")
                        new_content = ""
                        for i, part in enumerate(parts):
                            if i % 2 == 1: new_content += r"\textbf{" + escape_latex(part) + "}"
                            else: new_content += escape_latex(part)
                        content = new_content
                    else: content = escape_latex(content)
                    line = r"\item " + content
                else:
                    if in_list:
                        latex_lines.append(r"\end{itemize}")
                        in_list = False
                    if "**" in line:
                        parts = line.split("**")
                        new_line = ""
                        for i, part in enumerate(parts):
                            if i % 2 == 1: new_line += r"\textbf{" + escape_latex(part) + "}"
                            else: new_line += escape_latex(part)
                        line = new_line
                    else: line = escape_latex(line)
                latex_lines.append(line)
            if in_list: latex_lines.append(r"\end{itemize}")
            return "\n".join(latex_lines)

        # --- Escribir .tex ---
        with open(tex_path, "w", encoding="utf-8") as f:
            # Preamble
            f.write(r"""\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{graphicx}
\usepackage{geometry}
\usepackage{hyperref}
\usepackage{float}
\usepackage{parskip}
\usepackage{caption}
\geometry{a4paper, margin=1in}

\title{Reporte Automático de Minería de Datos}
\author{Hector Manuel Eguiarte Carlos}
\date{\today}

\begin{document}

""")

            # --- PORTADA ORDENADA ---
            if has_logo:
                f.write(r"""
\begin{titlepage}
    \centering
    \vspace*{1cm}

#     % Logo centrado y bien escalado
    \includegraphics[width=0.5\textwidth]{Logo.jpg}

    \vspace{2cm}

    {\Huge \textbf{Reporte de Proyecto de Minería de Datos}\par}

    \vspace{1cm}

    {\Large Análisis Automático y Generación de Insights con IA\par}

    \vspace{3cm}

    {\Large \textbf{Autores del Proyecto:}\par}
    \vspace{0.5cm}
    {\Large Hector Manuel Eguiarte Carlos\par}
    \vspace{0.2cm}
    {\Large Sinuhe Tijash Salamanca Ramos\par}

    \vfill

    {\large \today\par}
\end{titlepage}
""")
            else:
                f.write(r"\maketitle")

            f.write(r"\tableofcontents" + "\n")
            f.write(r"\newpage" + "\n")

            # --- SECCIÓN: METODOLOGÍA (Estructura Solicitada) ---
            f.write(r"\section{Metodología y Pipeline de Generación}" + "\n")
            f.write(r"El proceso de análisis de datos automatizado implementado en este proyecto sigue una arquitectura secuencial que garantiza la integridad y reproducibilidad de los resultados. A continuación se describen las etapas clave del pipeline:" + "\n\n")

            f.write(r"\begin{enumerate}" + "\n")
            f.write(r"\item \textbf{Carga del CSV:} Ingesta del dataset utilizando la librería Pandas, incluyendo detección automática de la codificación (UTF-8 o Latin-1) para asegurar la lectura correcta de caracteres especiales." + "\n")
            f.write(r"\item \textbf{Validación:} Verificación de requisitos mínimos para el análisis estadístico, asegurando que el dataset cuente con al menos 2000 registros y 10 columnas." + "\n")
            f.write(r"\item \textbf{Estadísticas:} Cálculo de medidas descriptivas fundamentales: moda y frecuencia para variables categóricas, y conteo de valores nulos (sparsity) para evaluar la calidad de los datos." + "\n")
            f.write(r"\item \textbf{Visualizaciones:} Generación dinámica de gráficos exploratorios (EDA), incluyendo histogramas para distribuciones, diagramas de caja (boxplots) y gráficos de barras." + "\n")
            f.write(r"\item \textbf{Outliers:} Detección de valores atípicos mediante el método robusto del Rango Intercuartil (IQR), identificando puntos extremos que podrían sesgar el análisis." + "\n")
            f.write(r"\item \textbf{Correlaciones:} Análisis de relaciones lineales entre variables numéricas mediante la matriz de correlación de Pearson y generación de mapas de calor (Heatmaps)." + "\n")
            f.write(r"\item \textbf{Integración con ChatGPT (IA):} Envío de los metadatos estadísticos procesados a un Modelo de Lenguaje Grande (LLM) para obtener una interpretación semántica, hallazgos clave y recomendaciones." + "\n")
            f.write(r"\item \textbf{Generación del reporte final:} Compilación automática de todos los artefactos generados (texto, tablas, gráficas) en un documento PDF estructurado y profesional." + "\n")
            f.write(r"\end{enumerate}" + "\n")

            f.write(r"\newpage" + "\n")

            # Diagrama
            f.write(r"\subsection*{Arquitectura del Flujo de Datos}" + "\n")
            diagrama_path = "diagrama_flujo.png"
            if os.path.exists(os.path.join(self.output_dir, diagrama_path)):
                f.write(r"\begin{figure}[H]" + "\n")
                f.write(r"\centering" + "\n")
                f.write(r"\includegraphics[width=1.0\textwidth, height=0.85\textheight, keepaspectratio]{" + diagrama_path + "}\n")
                f.write(r"\caption{Diagrama de Flujo Automatizado}\n")
                f.write(r"\end{figure}" + "\n")

                # Descripción Diagrama
                desc = self.graficos_descripciones.get(diagrama_path, "")
                if desc:
                    f.write(r"\vspace{0.2cm}" + "\n")
                    f.write(r"\textit{\textbf{Análisis Gráfico:} " + escape_latex(desc) + "}\n")

            f.write(r"\newpage" + "\n")

            # Visualizaciones con Descripciones
            f.write(r"\section{Evidencia Gráfica del Análisis}" + "\n")
            f.write(r"A continuación se presentan las visualizaciones generadas automáticamente." + "\n\n")

            for filename in os.listdir(self.output_dir):
                if filename.endswith(".png") and "diagrama" not in filename:
                    clean_title = filename.replace("_", " ").replace(".png", "").title()
                    if filename == "Logo.jpg": continue

                    f.write(r"\begin{figure}[H]" + "\n")
                    f.write(r"\centering" + "\n")
                    f.write(r"\includegraphics[width=0.85\textwidth]{" + filename + "}\n")
                    f.write(r"\caption{" + escape_latex(clean_title) + "}\n")
                    f.write(r"\end{figure}" + "\n")

                    # --- AQUI INSERTAMOS LA DESCRIPCION ---
                    descripcion = self.graficos_descripciones.get(filename, "")
                    if descripcion:
                        f.write(r"\vspace{-0.3cm}" + "\n") # Acercar un poco el texto a la figura
                        f.write(r"\noindent\fbox{\parbox{\textwidth}{\small \textbf{Interpretación:} " + escape_latex(descripcion) + "}}\n")

                    f.write(r"\vspace{0.5cm}" + "\n") # Espacio antes de la siguiente figura

            f.write(r"\newpage" + "\n")

            # IA
            f.write(r"\section{Interpretación de Inteligencia Artificial}" + "\n")
            latex_ia_content = markdown_to_latex(texto_ia)
            f.write(latex_ia_content)

            f.write(r"\newpage" + "\n")

            # Conclusiones Auto
            f.write(r"\section{Conclusiones Técnicas Automáticas}" + "\n")
            conclusiones_auto = self.generar_conclusiones_automaticas()
            latex_conclusiones = markdown_to_latex(conclusiones_auto)
            f.write(latex_conclusiones)

            f.write(r"\end{document}")

        print(f"✅ Archivo LaTeX generado exitosamente en: {tex_path}")

    def generar_reporte_completo(self):
        """Orquesta todo el flujo"""
        self.limpiar_output()

        if self.cargar_y_validar():
            self.analisis_estadistico()
            self.detectar_outliers()
            self.visualizaciones()
            self.analisis_correlaciones()
            self.generar_diagrama_flujo()

            texto_ia = self.consultar_ia_generativa()
            self.generar_latex(texto_ia)

            print("\n✅ PROCESO COMPLETADO. Revisa la carpeta 'output'.")
            return texto_ia

try:
    API_KEY = userdata.get('GEMINI_API_KEY')
except:
    import getpass
    API_KEY = getpass.getpass("Introduce tu API Key: ")

analizador = AnalizadorCSV("Mineria_data.csv", API_KEY)
analizador.generar_reporte_completo()

analizador.descargar_resultados()

